version: 0.2
            
phases:

  install:
    runtime-versions:
      golang: 1.18

  build:
    commands:

      # Build our application
      - go build -o app

artifacts:
  files:
    - app
    - appspec.yml
    - buildspec.yml
    - config/*
    - codedeploy/*
    - cloudformation/*
